services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: irvansn/go-find-helpers:latest
    pull_policy: always
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - XDT_CALLBACK_VERIFICATION=${XDT_CALLBACK_VERIFICATION}
      - XDT_SECRET_API_KEY=${XDT_SECRET_API_KEY}
      - OPEN_API_KEY=${OPEN_API_KEY}
volumes:
  db:
    driver: local